# ============================================================================
# Data Validation Pipeline Environment - SEC Filings Project
# Purpose: Great Expectations validation, S3 integration, schema validation
# Compatible with: finrag_aws_etl_env (team's environment)
# ============================================================================
#
# INSTALLATION INSTRUCTIONS:
# --------------------------
#
# STEP 0: Clean existing environments (if necessary)
#   conda deactivate
#   conda env remove -n sec_validation_env
#   conda clean --all --yes
#
# STEP 1: Install mamba first (for faster installation)
#   conda install -n base -c conda-forge mamba
#
# STEP 2: Create environment using mamba (MUCH faster)
#   mamba env create -f environment.yml
#   # OR using conda (slower):
#   conda env create -f environment.yml
#
# STEP 3: Activate environment
#   conda activate sec_validation_env
#
# STEP 4: Verify installation
#   python -c "import great_expectations, boto3, pandas; print('Setup complete!')"
#   python -c "import sys; print(f'Python: {sys.version}')"
#
# UPDATE ENVIRONMENT:
#   mamba env update -f environment.yml --prune
#
# EXPORT FOR REPRODUCIBILITY:
#   conda env export --no-builds > environment.lock.yml
#
# ============================================================================

name: sec_validation_env

channels:
  - conda-forge
  - defaults

dependencies:
  # ----- Python Version (matching team's version) -----
  - python=3.11.14
  
  # ----- Build Tools -----
  - setuptools>=69.0.0
  - pip>=24.0
  
  # ----- CRITICAL COMPATIBILITY (matching team's versions) -----
  # These MUST match for data interchange
  - pyarrow=14.0.0         # Exact match for parquet compatibility
  - numpy>=1.24.0,<2.0     # Compatible range with team
  
  # ----- AWS Core (matching team's AWS stack) -----
  - boto3>=1.35.0,<1.36
  - botocore>=1.35.0,<1.36
  - s3fs>=2024.6.0
  
  # ----- Data Processing Core (compatible with team) -----
  - pandas=2.0.3           # Your current version, compatible with team's range
  - scipy=1.11.0           # Your current version, matches team's range
  
  # ----- Configuration & Utilities (shared with team) -----
  - python-dotenv>=1.0.0
  - pyyaml>=6.0
  - click>=8.1.7
  - rich>=13.7.0
  - tabulate>=0.9.0
  
  # ----- Testing Framework (compatible versions) -----
  - pytest>=7.4.3,<9.0
  - pytest-cov>=4.1.0
  - pytest-mock>=3.12.0
  
  # ----- Monitoring & Logging -----
  - psutil>=5.9.6
  
  # ----- Visualization (for reports) -----
  - matplotlib>=3.7.3
  - seaborn>=0.13.0
  - plotly>=5.18.0
  
  # ----- Email Support -----
  # Email libraries are typically pure Python, safe for pip
  
  # ----- Progress Display -----
  - tqdm>=4.66.0
  
  # ============================================================================
  # PIP-ONLY PACKAGES
  # These packages are not available in conda-forge or have better pip versions
  # CRITICAL: Using --no-deps to prevent pip from overriding conda packages
  # ============================================================================
  - pip:
      # Great Expectations - not in conda-forge, must use pip
      - great-expectations==0.18.8
      
      # MLflow for ML tracking (if needed)
      - mlflow==2.8.0
      
      # MLflow dependencies
      - flask>=2.2.0
      - sqlalchemy>=1.4.0
      - alembic>=1.8.0
      - markdown>=3.3
      - querystring-parser>=1.2.4
      - sqlparse>=0.4.0
      - gitpython>=3.1.0
      - databricks-cli>=0.18
      - docker>=6.0.0
      - gunicorn>=20.1.0
      - cloudpickle>=2.2.0
      - packaging>=21.3
      - importlib-metadata>=6.0.0
      - protobuf>=3.20.0
      
# ============================================================================
#
# INTEGRATION NOTES:
# ------------------
#
# This environment is designed to be compatible with finrag_aws_etl_env:
#
# 1. SHARED PACKAGES (exact versions for compatibility):
#    - pyarrow=14.0.0 (CRITICAL for parquet interchange)
#    - boto3/botocore (same AWS SDK version)
#    - pandas/numpy (compatible versions)
#
# 2. YOUR SPECIFIC PACKAGES:
#    - great-expectations (validation framework)
#    - mlflow (optional, for ML tracking)
#
# 3. TO MERGE WITH TEAM'S ENVIRONMENT:
#    Simply add the pip section to their environment.yml:
#    ```yaml
#    - pip:
#        - great-expectations==0.18.8
#        - mlflow==2.8.0
#    ```
#
# 4. DATA INTERCHANGE:
#    - Use parquet format for data exchange
#    - Ensure datetime columns use same timezone (UTC recommended)
#    - Use same compression (snappy is default)
#
# ============================================================================
#
# TROUBLESHOOTING:
# ----------------
#
# "Package conflicts":
#   mamba env create -f environment.yml --no-default-packages
#
# "ImportError after installation":
#   pip install --no-deps great-expectations==0.18.8
#   pip install <missing_dependency>
#
# Check environment health:
#   conda list | grep -E "pyarrow|pandas|numpy|boto3"
#
# Test S3 connection:
#   python -c "import boto3; s3=boto3.client('s3'); print(s3.list_buckets())"
#
# ============================================================================