# environment.yml
# FinSight - Financial Intelligence Platform for SEC Filings
# 
# This environment is for the data ingestion and ETL pipeline components
# 
# Usage:
#   Create environment: conda env create -f environment.yml
#   Activate: conda activate finsight
#   Update: conda env update -f environment.yml --prune
#   Remove: conda env remove -n finsight

name: finsight-venv

channels:
  - conda-forge
  - defaults

dependencies:
  # ============================================
  # Python Version
  # ============================================
  - python=3.11
  
  # ============================================
  # Package Management
  # ============================================
  - pip=25.2
  - setuptools=80.9.0
  - wheel=0.45.1
  
  # ============================================
  # Core System Libraries (handled by conda)
  # ============================================
  - openssl=3.0.*
  - ca-certificates
  
  # ============================================
  # Pip Packages
  # ============================================
  - pip:
      # ===== AWS Services =====
      - boto3==1.40.59
      - botocore==1.40.59
      - s3transfer==0.14.0
      
      # ===== Data Processing & Analysis =====
      - pandas==1.5.3
      - numpy==1.26.4
      - polars==1.34.0
      - pyarrow==22.0.0
      
      # ===== SEC EDGAR Data Collection =====
      - sec-edgar-downloader==5.0.3
      
      # ===== Web Scraping & HTML Parsing =====
      - beautifulsoup4==4.12.2
      - lxml==4.9.3
      - soupsieve==2.8
      - cssutils==2.9.0
      
      # ===== Natural Language Processing =====
      - nltk==3.9.2
      - regex==2025.10.23
      
      # ===== HTTP & Requests =====
      - requests==2.31.0
      - urllib3==1.26.20
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - idna==3.11
      
      # ===== Configuration & Environment =====
      - python-dotenv==1.1.1
      - pyyaml==6.0.3
      
      # ===== Templating =====
      - jinja2==3.1.6
      - markupsafe==3.0.3
      
      # ===== Utilities =====
      - click==8.3.0
      - tqdm==4.66.0
      - colorama==0.4.6
      - pygments==2.19.2
      
      # ===== Parallel Processing =====
      - joblib==1.5.2
      - pathos==0.3.1
      - multiprocess==0.70.18
      - dill==0.4.0
      - pox==0.3.6
      - ppft==1.7.7
      
      # ===== Rate Limiting =====
      - pyrate-limiter==3.9.0
      
      # ===== Date/Time Handling =====
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      
      # ===== Data Serialization =====
      - xmltodict==1.0.2
      
      # ===== Testing =====
      - pytest==8.4.2
      - moto==5.1.15
      - responses==0.25.8
      - pluggy==1.6.0
      - iniconfig==2.3.0
      - tomli==2.3.0
      - exceptiongroup==1.3.0
      
      # ===== Security & Cryptography =====
      - cryptography==46.0.3
      - cffi==2.0.0
      - pycparser==2.23
      
      # ===== Web Framework (for moto testing) =====
      - werkzeug==3.1.3
      
      # ===== Miscellaneous =====
      - six==1.17.0
      - jmespath==1.0.1
      - packaging==25.0
      - typing-extensions==4.15.0